### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/alexa-verifier#65]
Here's what I'm thinking about for the next major release (3.0.0):

* require node v12.17 and up
* switch to pure es module
* drop commonjs
* switch to es6 everywhere (`const`, `let`, spread, destructuring, etc.)
* ditch old callback style in favor of `async` function (finally!)
* update all deps

These are just my current musings. Open for thoughts/ideas/suggestions.

**Comment by mreinstein** [comment]
One wrinkle with ditching the callback style is alexa-verifier-middleware is a major consumer of this module, which is an express middleware, and express _still_ doesn't support async middlewares. It might be better to hold off on this particular item until express supports that out of the box (v5 does I think, but it's perpetually marked as alpha)

**Comment by tejashah88** [comment]
@mreinstein We could have it so v3 could expose a `.callback()` and a `.promise()` function, to allow flexibility. The nice thing is that Node has a native method to promisify callback-based functions, so that should be easy to add.

One thing to note is that it'll be a long while before express v4 and below are so rarely used that we can completely ditch the callback style.

**Comment by mreinstein** [comment]
I did all of this _except_ for the async function, since express still lacks async/await middlewares. :(
